### ISSUE TITLE
online access to old WordPress media gallery

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/sl-sludgeline#12]
Turns out, it's time for us to add image captions to [published posts](https://sludge.ghost.io/ghost/#/posts?type=published) (sortable by oldest first) from 2018 and on.

I think that our old WP image gallery lives in a big JSON bundle in your backups, whether on your machine locally or in the cloud somewhere. 

Is there any super-fast way to throw that up online somewhere for Donny and me to reference? Since old [WPengine archive](https://sludgemedia.wpengine.com/wp-login) is down, now.

**Comment by unitof** [comment]
[wp_ghost_export.json](https://github.com/yescomment/sl-sludgeline/files/13890518/wp_ghost_export.json)
Here's the JSON of all posts that I imported, but that does not include images.

However let me know if it _does_ have the captions you're looking for. If not, I can dig up that full WP backup!
