### ISSUE TITLE
create field for "CTA free lede"

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/sl-sludgeline#14]
currently in settings --> design --> sitewide, we have a nice new CTA paid title and CTA lede. But we don't have a lede for CTA free title, as you showed in the site logic.

**Comment by unitof** [comment]
Related: filed a bug with Ghost for the annoying error you're seeing, despite us indeed using all defined custom variables! https://github.com/TryGhost/gscan/issues/523
