### ISSUE TITLE
Create Google News Sitemap

### ISSUE THREAD

**Issue by donnysludge** [yescomment/sl-sludgeline#20]

**Comment by davidmooreppf** [comment]
In G-Search [Console](https://search.google.com/search-console?resource_id=sc-domain%3Areadsludge.com), under Sitemaps: Missing XML tag, please add it and resubmit

<img width="1057" alt="Screenshot 2024-07-09 at 12 10 30 PM" src="https://github.com/yescomment/sl-sludgeline/assets/116819/17f6dec3-772a-436f-89e0-4da9d5c37b2e">

**Comment by davidmooreppf** [comment]
we'll see if you can do this first thing today

**Comment by davidmooreppf** [comment]
From news.google.com, other sites show all posts going back weeks. We were following Google's recommendation to only show past couple days. Gotta figure out if we can switch ours.
