### ISSUE TITLE
put GA on RS

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/sl-sludgeline#27]
Please make a task to put G-analytics on RS by end of week, Aug. 2. We'll need it. cc @donnysludge

I have google accounts for davidrussellmoore and for david @ readsludge dot com, in terms of which analytics code to inject, but I don't think that matters , your email has admin.

**Comment by unitof** [comment]
I'll use the account associated with the Search Console/Google News account we set up previously.

For my planning: do you just anticipate wanting GA, or plan to use other Google script products (Google Ads, etc.) down the road? If so, should use GTM instead.

**Comment by davidmooreppf** [comment]
well, as of right now I think just GA. I am not anticipating those others.
