### ISSUE TITLE
Add signup box to homepage

### ISSUE THREAD

**Issue by donnysludge** [yescomment/sl-sludgeline#32]
Perhaps below the "featured section"? Or above that section? Either way would probably be fine.

**Comment by davidmooreppf** [comment]
ha yep I had this one in old #18 that's been sitting there for months, or a year since our Ghost switch. Doing now.

**Comment by davidmooreppf** [comment]
thanks to Jacob's ingenious work, we can change the copy in the homepage signup box using the fields in settings --> design --> sitewide --> “CTA home free title” and “CTA home nonmember title"
