### ISSUE TITLE
Signup page tier names to Sludge Blue™

### ISSUE THREAD

**Issue by unitof** [yescomment/sl-sludgeline#33]
See 19184986cfa1723efd35d9d68144dcc8f54c95a2. CSS doesn't work as they are in an iframe. Can I redefine `--brandcolor` inline instead?

**Comment by davidmooreppf** [comment]
And the links in our emails sent out also inherited the Accent Color. Getting them back to blue would be great. cc @donnysludge

**Comment by unitof** [comment]
Closed in 4ea3ce602743199a5e9a79fa441a6d61b53152fa (after a bunch of whimsy)

**Comment by davidmooreppf** [comment]
Very briefly, reminding myself - last week we discovered that when using Ghost Pro, the site lower-right corner Subscribe button has to use the Accent Color (in settings). This means that our links are Sludge blue, as are the boxes in our portal. So currently, on mobile, the *lower right* subscribe button is Sludge blue. But that's not very grabby for a mobile visitor.

Just to ask the question, can mobile Sludge have a different accent color? I reckon not!
