### ISSUE TITLE
check a glitch in Outpost offer creation?

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/sl-sludgeline#34]
Visit Sludge's Outpost [offers](https://readsludgecom.outpost.pub/home#/offers), click add new offer, try to create an offer with a Free Trial of 2 free months, and the resulting offer that 'saves' defaults to 7 days free. Weird. cc @donnysludge

<img width="459" alt="Screenshot 2024-08-28 at 11 02 07 AM" src="https://github.com/user-attachments/assets/a95c7eff-1bc7-43ac-ae34-d86bda9a8cb5">

**Comment by unitof** [comment]
Definitely an Outpost bug, just reported to support@outpost.pub (cc'd David).

However a workaround is you can set these up natively in Ghost, which seems to work as expected.

(Outpost is just an alternative frontend to Ghost Offers API, so creating in either place syncs to other.)

I set up readsludge.com/2weeksfree—feel free to use, edit, or delete.


https://github.com/user-attachments/assets/f02ba93f-9d8a-439e-8e86-ad69538bfb31

↑ creating 2-week trial in Ghost
↓ that offer then shows (correctly) in Outpost

https://github.com/user-attachments/assets/438d4ea9-bd31-413a-a1bb-c9140d975a4b

Closing as workaround is just as good, and Outpost bug reported upstream.
