### ISSUE TITLE
question about above-the-fold on Nikko theme

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/sl-sludgeline#38]
Forgive the basic question. We're just checking that above the fold homepage on [Nikko](https://sludge2.ghost.io/), we can change the box-in-a-box layout to anything we want, yeah? We'll have a signup field there for email, just confirming that's pretty quick next week. cc @donnysludge

**Comment by unitof** [comment]
Could you screenshot what you're referring to? Multiple if it shows up multiple places.

**Comment by davidmooreppf** [comment]
I was referring to the main body above-the-fold on the homepage. It's since changed on Sludge2, but here is the part:

<img width="583" alt="Screenshot 2024-10-24 at 7 40 34 PM" src="https://github.com/user-attachments/assets/b4e632f5-9d71-46f5-bb08-3dee672f6b22">

**Comment by davidmooreppf** [comment]
Yeah, clearly, I just wasn't looking at the [gallery](https://brightthemes.com/showcase/nikko). cc @donnysludge
