### ISSUE TITLE
change copy on post previews

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/sl-sludgeline#4]
Currently for new [post](https://www.readsludge.com/2023/08/11/chemical-company-funded-senators-float-watered-down-pfas-bill/) visitors, the built-in big subscribe block reads, "This post is for subscribers only." 

Goal is to make that text more friendly for now. 

Let's use, "Read the whole story for free. Subscribe to Sludge news with your email."

<img width="795" alt="Screen Shot 2023-08-21 at 1 19 30 PM" src="https://github.com/yescomment/sl-sludgeline/assets/116819/e4362045-17e1-4924-afa0-707dae2f86ed">

**Comment by unitof** [comment]
If okay, I just modified grammar to

```diff
- Read the whole story for free. Subscribe to Sludge news with your email.
+ Read the whole story for free: subscribe to Sludge News with your email
```

to better match other possible message there.

(which are:)

_If gated for paid members only:_

<h2>This {{#is "page"}}page{{else}}post{{/is}} is for paying subscribers only</h2>

_If gated for logged in members only:_

<h2>Read the whole story for free: subscribe to Sludge news with your email</h2>

_If gated for a specific tier of members only:_

<h2>This {{#is "page"}}page{{else}}post{{/is}} is for subscribers on the {{tiers}} only </h2>

**Comment by davidmooreppf** [comment]
I've been informed my syntax was confusing. Please change to: 

The full text of this story is for members only. To become a member, simply enter your email address. It’s free to join:

**Comment by unitof** [comment]
Can do.

Comma,
Jacob Ford
Designer <https://jacobford.com> About <https://nocomment.llc> Town
<https://geistlist.email>

**Comment by unitof** [comment]
How's this? Felt full line was a bit long for a header.
<img width="1249" alt="image" src="https://github.com/yescomment/sl-sludgeline/assets/2448782/6bc1361e-6ffd-49e2-a5a5-9f66978da37c">

**Comment by davidmooreppf** [comment]
great, thx

**Comment by davidmooreppf** [comment]
I've been informed I fumbled the copy again. Please try:

Unlock this story by signing up as a Sludge subscriber. It's free and gives you access to our full website.

**Comment by unitof** [comment]
No worries. Okay broken into 2 lines like this?
<img width="747" alt="image" src="https://github.com/yescomment/sl-sludgeline/assets/2448782/945ecd68-f2d9-4b72-aa13-db836d4019cc">

**Comment by davidmooreppf** [comment]
Thanks - I didn't emphasize enough that it's free - let's try this, input welcome:

Unlock the full story for free.

Sign up as a Sludge subscriber. It's free and gives you access to our full website.

**Comment by unitof** [comment]
Let's try it!

**Comment by davidmooreppf** [comment]
Time for a change, switch to:

Get this full story for free. Subscribe to Sludge for full access to our website.

**Comment by unitof** [comment]
Need a callout header (`h2`) and a body, so broke it down like this:
<img width="1531" alt="image" src="https://github.com/yescomment/sl-sludgeline/assets/2448782/c64b200c-4bf2-4f9a-8378-b6c44fd52909">
Correct?

**Comment by davidmooreppf** [comment]
That works.

Real quick, just for your input  - what about a late-breaking alternative:

Get this full story for free

Click the button below and enter your email address for full access to our website.

**Comment by unitof** [comment]
Don't think we need "click the button below" but I like emphasizing that the cost for full web access is just your email address. Maybe:

## Get this full story for free

Email subscribers get full website access for free.

[ Subscribe now ]

**Comment by davidmooreppf** [comment]
Good, your version please.

**Comment by davidmooreppf** [comment]
My bad, short-sighted work on my part. Turns out the paid-member-only block uses the very same "Email subscribers get..." line. And we're turning the paywall on tomorrow across the site. 

<img width="741" alt="Screen Shot 2023-10-31 at 1 45 31 PM" src="https://github.com/yescomment/sl-sludgeline/assets/116819/ae5343de-cf65-44f7-888c-ca74495e4408">

So please change the line "Email subscribers get..." to "Subscribers get our new stories over email the moment they're published."

**Comment by unitof** [comment]
Ah, yeah. Here's the breakdown of the logic, if it helps you write these in future:

https://github.com/yescomment/sl-sludgeline/blob/main/partials/content-cta.hbs

I can change the logic if we want, but if we stick with Ghost's out-of-the-box approach I need three versions of headline copy:

* for members-only articles, written for non-members
* for paid-only articles, written for free members
* for higher-tier articles, written for lower paying tiers (if you ever plan to do this)
