### ISSUE TITLE
breaker: URL structure changed with new Bold theme

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/sl-sludgeline#43]
Old URL structure had dates:

https://readsludge.com/2024/11/08/trump-selects-corporate-lobbyist-susie-wiles-as-chief-of-staff/

New theme doesn't:

https://readsludge.com/trump-selects-corporate-lobbyist-susie-wiles-as-chief-of-staff/

Roll back, or fix in Code Injection?

cc @donnysludge

**Comment by unitof** [comment]
Caused by upload of new routes.yaml file, fixed by merging back that permalink line
