### ISSUE TITLE
another redirect, and pinning down what causes strange URLs

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/sl-sludgeline#7]
Need another redirect on below. Drat.

Trying to figure this out. We saved a post and initially set it to paid members only in draft. 

Then we changed the post's visibility to public, and posted it and sent it to paid members. The URL in the email came out as:

https://readsludge.com/2023/11/02/untitled-2/

The URL should be what we just changed it to: 

https://readsludge.com/2023/11/02/aipac-dark-money-group-attack-ad-rashida-tlaib/

... I'm not sure what freaks out the Ghost, whether it's the change in visibility or what. The little preview of the URL in the right-hand side of the post editor in Ghost shows it to be normal before publishing-and-sending-email.

**Comment by unitof** [comment]
Redirect set: http://readsludge.com/2023/11/02/untitled-2/

Will see if I can replicate.

**Comment by unitof** [comment]
Shoot, did a whole screen recording last week, guess it didn't upload.

Long story short: haven't been able to replicated a post slug _changing_ after being manually set, but was able to find some conditions under which changing the title of a post _does not_ update the slug from the `untitled` default. Will post screen recording when I'm back at desktop.

But if you have any more info or can identify a case of the slug explicitly changing after being set, please send!
